; Song Naksolaat in Lightweight format (V1).
; Generated by Arkos Tracker 2.

Naksolaat_SongStart
	defb "ATLW"	; Format marker (LightWeight).
	defb 1	; Format version.
	defw Naksolaat_FmInstrumentTable
	defw Naksolaat_ArpeggioTable
	defw Naksolaat_PitchTable
; Table of the Subsongs.
	defw Naksolaat_Subsong0

; The Arpeggio table.
Naksolaat_ArpeggioTable
	defw 0

; The Pitch table.
Naksolaat_PitchTable
	defw 0

; The FM Instrument table.
Naksolaat_FmInstrumentTable
	defw Naksolaat_FmInstrument0
	defw Naksolaat_FmInstrument1
	defw Naksolaat_FmInstrument2

Naksolaat_FmInstrument0
	defb 255	; Speed.

Naksolaat_FmInstrument0_Loop	defb 0	; Volume: 0.

	defb 4	; End the instrument.
	defw Naksolaat_FmInstrument0_Loop	; Loops.

Naksolaat_FmInstrument1
	defb 0	; Speed.

	defb 61	; Volume: 15.

	defb 57	; Volume: 14.

	defb 53	; Volume: 13.

	defb 49	; Volume: 12.

	defb 45	; Volume: 11.

	defb 41	; Volume: 10.

	defb 37	; Volume: 9.

	defb 33	; Volume: 8.

	defb 29	; Volume: 7.

	defb 25	; Volume: 6.

	defb 21	; Volume: 5.

	defb 17	; Volume: 4.

	defb 13	; Volume: 3.

	defb 9	; Volume: 2.

	defb 5	; Volume: 1.

	defb 4	; End the instrument.
	defw Naksolaat_FmInstrument0_Loop	; Loop to silence.

Naksolaat_FmInstrument2
	defb 0	; Speed.

	defb 189	; Volume: 15.
	defb 25	; Arpeggio: 12.
	defb 11	; Noise: 11.

	defb 185	; Volume: 14.
	defb 27	; Arpeggio: 13.
	defb 10	; Noise: 10.

	defb 181	; Volume: 13.
	defb 33	; Arpeggio: 16.
	defb 9	; Noise: 9.

	defb 181	; Volume: 13.
	defb 19	; Arpeggio: 9.
	defb 8	; Noise: 8.

	defb 177	; Volume: 12.
	defb 1	; Arpeggio: 0.
	defb 7	; Noise: 7.

	defb 169	; Volume: 10.
	defb 19	; Arpeggio: 9.
	defb 6	; Noise: 6.

	defb 161	; Volume: 8.
	defb 29	; Arpeggio: 14.
	defb 5	; Noise: 5.

	defb 153	; Volume: 6.
	defb 1	; Arpeggio: 0.
	defb 4	; Noise: 4.

	defb 145	; Volume: 4.
	defb 1	; Arpeggio: 0.
	defb 3	; Noise: 3.

	defb 141	; Volume: 3.
	defb 1	; Arpeggio: 0.
	defb 2	; Noise: 2.

	defb 4	; End the instrument.
	defw Naksolaat_FmInstrument0_Loop	; Loop to silence.

; Song Naksolaat, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

Naksolaat_Subsong0
	defb 5	; Initial speed.

; The Linker.
; Pattern 0
Naksolaat_Subsong0_Loop
	defb 5	; State byte.
	defb 63	; New height.
	defw Naksolaat_Subsong0_Track11, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 1
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track4, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 2
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track2, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 3
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track5, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 4
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track3, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 5
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track7, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 6
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track6, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 7
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track8, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 8
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track9, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 9
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track10, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 10
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track0, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 11
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track12, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 12
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track13, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 13
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track14, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 14
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track6, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 15
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track8, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 16
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track9, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 17
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track10, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 18
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track15, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 19
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track16, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 20
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track17, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 21
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track18, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 22
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track6, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 23
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track8, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 24
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track9, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 25
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track10, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 26
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track11, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

; Pattern 27
	defb 1	; State byte.
	defw Naksolaat_Subsong0_Track4, Naksolaat_Subsong0_Track1, Naksolaat_Subsong0_Track1	; The tracks.

	defb 0	; End of the subsong.
	defw Naksolaat_Subsong0_Loop

; The Tracks.
Naksolaat_Subsong0_Track0
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 63, 84	; Escaped note: 84.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 63, 86	; Escaped note: 86.
	defb 63, 79	; Escaped note: 79.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 19	; Note: 43.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 63, 76	; Escaped note: 76.
	defb 24	; Note: 48.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 63, 84	; Escaped note: 84.
	defb 63, 79	; Escaped note: 79.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 63, 84	; Escaped note: 84.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 152	; Note: 48.
	defb 2	; New instrument: 1.
	defb 63, 88	; Escaped note: 88.
	defb 63, 91	; Escaped note: 91.
	defb 63, 21	; Escaped note: 21.
	defb 63, 88	; Escaped note: 88.
	defb 63, 21	; Escaped note: 21.
	defb 63, 86	; Escaped note: 86.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 84	; Escaped note: 84.
	defb 2	; New instrument: 1.
	defb 63, 79	; Escaped note: 79.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 16	; Note: 40.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 79	; Escaped note: 79.
	defb 2	; New instrument: 1.
	defb 63, 81	; Escaped note: 81.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 21	; Note: 45.
	defb 63, 21	; Escaped note: 21.
	defb 0	; Note: 24.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 19	; Escaped note: 19.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track1
	defb 61, 63	; Long wait: 64.


Naksolaat_Subsong0_Track2
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 7	; Note: 31.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 63, 21	; Escaped note: 21.
	defb 36	; Note: 60.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 28	; Note: 52.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 161	; Note: 57.
	defb 2	; New instrument: 1.
	defb 31	; Note: 55.
	defb 63, 21	; Escaped note: 21.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 164	; Note: 60.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 63, 21	; Escaped note: 21.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 31	; Note: 55.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 166	; Note: 62.
	defb 2	; New instrument: 1.
	defb 31	; Note: 55.
	defb 63, 21	; Escaped note: 21.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 28	; Note: 52.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 63, 21	; Escaped note: 21.
	defb 36	; Note: 60.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 156	; Note: 52.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 63, 21	; Escaped note: 21.
	defb 33	; Note: 57.
	defb 63, 21	; Escaped note: 21.
	defb 0	; Note: 24.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 19	; Escaped note: 19.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track3
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 63, 72	; Escaped note: 72.
	defb 63, 21	; Escaped note: 21.
	defb 33	; Note: 57.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 7	; Note: 31.
	defb 45	; Note: 69.
	defb 63, 21	; Escaped note: 21.
	defb 33	; Note: 57.
	defb 63, 21	; Escaped note: 21.
	defb 36	; Note: 60.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 171	; Note: 67.
	defb 2	; New instrument: 1.
	defb 31	; Note: 55.
	defb 45	; Note: 69.
	defb 63, 21	; Escaped note: 21.
	defb 43	; Note: 67.
	defb 63, 21	; Escaped note: 21.
	defb 28	; Note: 52.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 173	; Note: 69.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 31	; Note: 55.
	defb 63, 21	; Escaped note: 21.
	defb 45	; Note: 69.
	defb 63, 21	; Escaped note: 21.
	defb 45	; Note: 69.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 164	; Note: 60.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 63, 21	; Escaped note: 21.
	defb 63, 74	; Escaped note: 74.
	defb 63, 21	; Escaped note: 21.
	defb 31	; Note: 55.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 173	; Note: 69.
	defb 2	; New instrument: 1.
	defb 38	; Note: 62.
	defb 31	; Note: 55.
	defb 63, 21	; Escaped note: 21.
	defb 43	; Note: 67.
	defb 63, 21	; Escaped note: 21.
	defb 28	; Note: 52.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 173	; Note: 69.
	defb 2	; New instrument: 1.
	defb 31	; Note: 55.
	defb 63, 72	; Escaped note: 72.
	defb 63, 21	; Escaped note: 21.
	defb 33	; Note: 57.
	defb 63, 21	; Escaped note: 21.
	defb 36	; Note: 60.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 173	; Note: 69.
	defb 2	; New instrument: 1.
	defb 28	; Note: 52.
	defb 33	; Note: 57.
	defb 63, 21	; Escaped note: 21.
	defb 63, 74	; Escaped note: 74.
	defb 63, 21	; Escaped note: 21.
	defb 63, 74	; Escaped note: 74.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 19	; Escaped note: 19.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track4
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 2	; Note: 26.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 19	; Escaped note: 19.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track5
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 7	; Note: 31.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 2	; Note: 26.
	defb 36	; Note: 60.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 28	; Note: 52.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 161	; Note: 57.
	defb 2	; New instrument: 1.
	defb 31	; Note: 55.
	defb 2	; Note: 26.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 164	; Note: 60.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 0	; Note: 24.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 2	; New instrument: 1.
	defb 31	; Note: 55.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 166	; Note: 62.
	defb 2	; New instrument: 1.
	defb 31	; Note: 55.
	defb 0	; Note: 24.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 2	; New instrument: 1.
	defb 28	; Note: 52.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 19	; Escaped note: 19.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 63, 19	; Escaped note: 19.
	defb 36	; Note: 60.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 156	; Note: 52.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 63, 21	; Escaped note: 21.
	defb 33	; Note: 57.
	defb 63, 21	; Escaped note: 21.
	defb 33	; Note: 57.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 156	; Note: 52.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track6
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 21	; Note: 45.
	defb 63, 21	; Escaped note: 21.
	defb 21	; Note: 45.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 63, 21	; Escaped note: 21.
	defb 24	; Note: 48.
	defb 63, 21	; Escaped note: 21.
	defb 21	; Note: 45.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 144	; Note: 40.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 63, 21	; Escaped note: 21.
	defb 21	; Note: 45.
	defb 63, 21	; Escaped note: 21.
	defb 19	; Note: 43.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 144	; Note: 40.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 14	; Note: 38.
	defb 63, 21	; Escaped note: 21.
	defb 16	; Note: 40.
	defb 63, 21	; Escaped note: 21.
	defb 19	; Note: 43.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 63, 21	; Escaped note: 21.
	defb 21	; Note: 45.
	defb 63, 21	; Escaped note: 21.
	defb 21	; Note: 45.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 144	; Note: 40.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 63, 21	; Escaped note: 21.
	defb 24	; Note: 48.
	defb 63, 21	; Escaped note: 21.
	defb 26	; Note: 50.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 24	; Note: 48.
	defb 16	; Note: 40.
	defb 63, 21	; Escaped note: 21.
	defb 19	; Note: 43.
	defb 63, 21	; Escaped note: 21.
	defb 21	; Note: 45.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 154	; Note: 50.
	defb 2	; New instrument: 1.
	defb 16	; Note: 40.
	defb 19	; Note: 43.
	defb 63, 21	; Escaped note: 21.
	defb 21	; Note: 45.
	defb 63, 21	; Escaped note: 21.
	defb 0	; Note: 24.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 19	; Escaped note: 19.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track7
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 63, 72	; Escaped note: 72.
	defb 2	; Note: 26.
	defb 33	; Note: 57.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 7	; Note: 31.
	defb 45	; Note: 69.
	defb 2	; Note: 26.
	defb 33	; Note: 57.
	defb 2	; Note: 26.
	defb 36	; Note: 60.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 171	; Note: 67.
	defb 2	; New instrument: 1.
	defb 31	; Note: 55.
	defb 45	; Note: 69.
	defb 2	; Note: 26.
	defb 43	; Note: 67.
	defb 2	; Note: 26.
	defb 28	; Note: 52.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 173	; Note: 69.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 31	; Note: 55.
	defb 2	; Note: 26.
	defb 45	; Note: 69.
	defb 2	; Note: 26.
	defb 45	; Note: 69.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 164	; Note: 60.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 0	; Note: 24.
	defb 63, 74	; Escaped note: 74.
	defb 0	; Note: 24.
	defb 31	; Note: 55.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 173	; Note: 69.
	defb 2	; New instrument: 1.
	defb 38	; Note: 62.
	defb 31	; Note: 55.
	defb 0	; Note: 24.
	defb 43	; Note: 67.
	defb 0	; Note: 24.
	defb 28	; Note: 52.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 173	; Note: 69.
	defb 2	; New instrument: 1.
	defb 31	; Note: 55.
	defb 63, 72	; Escaped note: 72.
	defb 63, 19	; Escaped note: 19.
	defb 33	; Note: 57.
	defb 63, 19	; Escaped note: 19.
	defb 36	; Note: 60.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 173	; Note: 69.
	defb 2	; New instrument: 1.
	defb 28	; Note: 52.
	defb 33	; Note: 57.
	defb 63, 21	; Escaped note: 21.
	defb 63, 74	; Escaped note: 74.
	defb 63, 21	; Escaped note: 21.
	defb 43	; Note: 67.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 19	; Escaped note: 19.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track8
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 21	; Note: 45.
	defb 2	; Note: 26.
	defb 21	; Note: 45.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 2	; Note: 26.
	defb 24	; Note: 48.
	defb 2	; Note: 26.
	defb 21	; Note: 45.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 144	; Note: 40.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 2	; Note: 26.
	defb 21	; Note: 45.
	defb 2	; Note: 26.
	defb 19	; Note: 43.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 144	; Note: 40.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 14	; Note: 38.
	defb 2	; Note: 26.
	defb 16	; Note: 40.
	defb 2	; Note: 26.
	defb 19	; Note: 43.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 0	; Note: 24.
	defb 21	; Note: 45.
	defb 0	; Note: 24.
	defb 21	; Note: 45.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 144	; Note: 40.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 0	; Note: 24.
	defb 24	; Note: 48.
	defb 0	; Note: 24.
	defb 19	; Note: 43.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 16	; Note: 40.
	defb 19	; Note: 43.
	defb 63, 19	; Escaped note: 19.
	defb 19	; Note: 43.
	defb 63, 19	; Escaped note: 19.
	defb 26	; Note: 50.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 16	; Note: 40.
	defb 14	; Note: 38.
	defb 63, 21	; Escaped note: 21.
	defb 16	; Note: 40.
	defb 63, 21	; Escaped note: 21.
	defb 2	; Note: 26.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 19	; Escaped note: 19.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track9
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 2	; Note: 26.
	defb 36	; Note: 60.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 24	; Note: 48.
	defb 33	; Note: 57.
	defb 2	; Note: 26.
	defb 33	; Note: 57.
	defb 2	; Note: 26.
	defb 31	; Note: 55.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 24	; Note: 48.
	defb 16	; Note: 40.
	defb 4	; Note: 28.
	defb 36	; Note: 60.
	defb 4	; Note: 28.
	defb 38	; Note: 62.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 21	; Note: 45.
	defb 14	; Note: 38.
	defb 4	; Note: 28.
	defb 63, 84	; Escaped note: 84.
	defb 4	; Note: 28.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 144	; Note: 40.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 5	; Note: 29.
	defb 45	; Note: 69.
	defb 5	; Note: 29.
	defb 63, 72	; Escaped note: 72.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 144	; Note: 40.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 5	; Note: 29.
	defb 63, 81	; Escaped note: 81.
	defb 5	; Note: 29.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 152	; Note: 48.
	defb 2	; New instrument: 1.
	defb 16	; Note: 40.
	defb 19	; Note: 43.
	defb 7	; Note: 31.
	defb 63, 86	; Escaped note: 86.
	defb 7	; Note: 31.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 21	; Note: 45.
	defb 19	; Note: 43.
	defb 9	; Note: 33.
	defb 21	; Note: 45.
	defb 9	; Note: 33.
	defb 7	; Note: 31.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track10
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 33	; Note: 57.
	defb 2	; Note: 26.
	defb 36	; Note: 60.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 24	; Note: 48.
	defb 33	; Note: 57.
	defb 2	; Note: 26.
	defb 33	; Note: 57.
	defb 2	; Note: 26.
	defb 31	; Note: 55.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 24	; Note: 48.
	defb 16	; Note: 40.
	defb 4	; Note: 28.
	defb 36	; Note: 60.
	defb 4	; Note: 28.
	defb 38	; Note: 62.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 21	; Note: 45.
	defb 14	; Note: 38.
	defb 4	; Note: 28.
	defb 63, 84	; Escaped note: 84.
	defb 4	; Note: 28.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 144	; Note: 40.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 5	; Note: 29.
	defb 45	; Note: 69.
	defb 5	; Note: 29.
	defb 63, 72	; Escaped note: 72.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 144	; Note: 40.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 5	; Note: 29.
	defb 63, 81	; Escaped note: 81.
	defb 5	; Note: 29.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 152	; Note: 48.
	defb 2	; New instrument: 1.
	defb 16	; Note: 40.
	defb 19	; Note: 43.
	defb 0	; Note: 24.
	defb 63, 86	; Escaped note: 86.
	defb 0	; Note: 24.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 21	; Note: 45.
	defb 19	; Note: 43.
	defb 7	; Note: 31.
	defb 21	; Note: 45.
	defb 7	; Note: 31.
	defb 7	; Note: 31.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track11
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 0	; Note: 24.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 19	; Escaped note: 19.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track12
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 63, 81	; Escaped note: 81.
	defb 2	; Note: 26.
	defb 63, 84	; Escaped note: 84.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 63, 86	; Escaped note: 86.
	defb 63, 79	; Escaped note: 79.
	defb 2	; Note: 26.
	defb 63, 81	; Escaped note: 81.
	defb 2	; Note: 26.
	defb 19	; Note: 43.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 63, 76	; Escaped note: 76.
	defb 24	; Note: 48.
	defb 2	; Note: 26.
	defb 63, 79	; Escaped note: 79.
	defb 2	; Note: 26.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 63, 84	; Escaped note: 84.
	defb 63, 79	; Escaped note: 79.
	defb 2	; Note: 26.
	defb 63, 81	; Escaped note: 81.
	defb 2	; Note: 26.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 0	; Note: 24.
	defb 63, 81	; Escaped note: 81.
	defb 0	; Note: 24.
	defb 63, 84	; Escaped note: 84.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 152	; Note: 48.
	defb 2	; New instrument: 1.
	defb 63, 88	; Escaped note: 88.
	defb 63, 86	; Escaped note: 86.
	defb 0	; Note: 24.
	defb 63, 76	; Escaped note: 76.
	defb 0	; Note: 24.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 81	; Escaped note: 81.
	defb 2	; New instrument: 1.
	defb 63, 79	; Escaped note: 79.
	defb 63, 81	; Escaped note: 81.
	defb 63, 19	; Escaped note: 19.
	defb 16	; Note: 40.
	defb 63, 19	; Escaped note: 19.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 79	; Escaped note: 79.
	defb 2	; New instrument: 1.
	defb 63, 81	; Escaped note: 81.
	defb 63, 84	; Escaped note: 84.
	defb 63, 21	; Escaped note: 21.
	defb 63, 91	; Escaped note: 91.
	defb 63, 21	; Escaped note: 21.
	defb 2	; Note: 26.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 86	; Escaped note: 86.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track13
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 63, 76	; Escaped note: 76.
	defb 7	; Note: 31.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 63, 81	; Escaped note: 81.
	defb 12	; Note: 36.
	defb 63, 21	; Escaped note: 21.
	defb 7	; Note: 31.
	defb 63, 21	; Escaped note: 21.
	defb 19	; Note: 43.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 76	; Escaped note: 76.
	defb 2	; New instrument: 1.
	defb 21	; Note: 45.
	defb 63, 76	; Escaped note: 76.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 81	; Escaped note: 81.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 81	; Escaped note: 81.
	defb 2	; New instrument: 1.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 63, 76	; Escaped note: 76.
	defb 7	; Note: 31.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 63, 84	; Escaped note: 84.
	defb 14	; Note: 38.
	defb 63, 21	; Escaped note: 21.
	defb 7	; Note: 31.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 63, 79	; Escaped note: 79.
	defb 7	; Note: 31.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 0	; Note: 24.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 19	; Escaped note: 19.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track14
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 63, 81	; Escaped note: 81.
	defb 2	; Note: 26.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 63, 76	; Escaped note: 76.
	defb 7	; Note: 31.
	defb 2	; Note: 26.
	defb 63, 79	; Escaped note: 79.
	defb 2	; Note: 26.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 63, 81	; Escaped note: 81.
	defb 12	; Note: 36.
	defb 2	; Note: 26.
	defb 7	; Note: 31.
	defb 2	; Note: 26.
	defb 19	; Note: 43.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 76	; Escaped note: 76.
	defb 2	; New instrument: 1.
	defb 21	; Note: 45.
	defb 63, 76	; Escaped note: 76.
	defb 2	; Note: 26.
	defb 63, 79	; Escaped note: 79.
	defb 2	; Note: 26.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 81	; Escaped note: 81.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 81	; Escaped note: 81.
	defb 2	; New instrument: 1.
	defb 0	; Note: 24.
	defb 63, 81	; Escaped note: 81.
	defb 0	; Note: 24.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 63, 76	; Escaped note: 76.
	defb 7	; Note: 31.
	defb 0	; Note: 24.
	defb 63, 79	; Escaped note: 79.
	defb 0	; Note: 24.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 63, 84	; Escaped note: 84.
	defb 14	; Note: 38.
	defb 63, 19	; Escaped note: 19.
	defb 7	; Note: 31.
	defb 63, 19	; Escaped note: 19.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 63, 79	; Escaped note: 79.
	defb 7	; Note: 31.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 63, 84	; Escaped note: 84.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 76	; Escaped note: 76.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track15
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 63, 79	; Escaped note: 79.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 63, 84	; Escaped note: 84.
	defb 9	; Note: 33.
	defb 63, 81	; Escaped note: 81.
	defb 9	; Note: 33.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 79	; Escaped note: 79.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 24	; Note: 48.
	defb 7	; Note: 31.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 135	; Note: 31.
	defb 2	; New instrument: 1.
	defb 21	; Note: 45.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 63, 84	; Escaped note: 84.
	defb 9	; Note: 33.
	defb 63, 86	; Escaped note: 86.
	defb 9	; Note: 33.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 79	; Escaped note: 79.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 154	; Note: 50.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 7	; Note: 31.
	defb 21	; Note: 45.
	defb 7	; Note: 31.
	defb 9	; Note: 33.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 135	; Note: 31.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track16
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 63, 79	; Escaped note: 79.
	defb 2	; Note: 26.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 63, 84	; Escaped note: 84.
	defb 14	; Note: 38.
	defb 63, 81	; Escaped note: 81.
	defb 14	; Note: 38.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 79	; Escaped note: 79.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 63, 81	; Escaped note: 81.
	defb 2	; Note: 26.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 24	; Note: 48.
	defb 12	; Note: 36.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 140	; Note: 36.
	defb 2	; New instrument: 1.
	defb 21	; Note: 45.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 147	; Note: 43.
	defb 2	; New instrument: 1.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 63, 84	; Escaped note: 84.
	defb 9	; Note: 33.
	defb 63, 86	; Escaped note: 86.
	defb 9	; Note: 33.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 79	; Escaped note: 79.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 191, 21	; Escaped note: 21.
	defb 2	; New instrument: 1.
	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 154	; Note: 50.
	defb 2	; New instrument: 1.
	defb 19	; Note: 43.
	defb 12	; Note: 36.
	defb 21	; Note: 45.
	defb 12	; Note: 36.
	defb 9	; Note: 33.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 135	; Note: 31.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track17
	defb 132	; Note: 28.
	defb 2	; New instrument: 1.
	defb 63, 79	; Escaped note: 79.
	defb 4	; Note: 28.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 16	; Note: 40.
	defb 63, 84	; Escaped note: 84.
	defb 4	; Note: 28.
	defb 63, 81	; Escaped note: 81.
	defb 4	; Note: 28.
	defb 26	; Note: 50.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 84	; Escaped note: 84.
	defb 2	; New instrument: 1.
	defb 16	; Note: 40.
	defb 63, 86	; Escaped note: 86.
	defb 2	; Note: 26.
	defb 19	; Note: 43.
	defb 2	; Note: 26.
	defb 21	; Note: 45.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 88	; Escaped note: 88.
	defb 2	; New instrument: 1.
	defb 14	; Note: 38.
	defb 63, 86	; Escaped note: 86.
	defb 2	; Note: 26.
	defb 63, 84	; Escaped note: 84.
	defb 2	; Note: 26.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 81	; Escaped note: 81.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 84	; Escaped note: 84.
	defb 2	; New instrument: 1.
	defb 63, 21	; Escaped note: 21.
	defb 31	; Note: 55.
	defb 63, 21	; Escaped note: 21.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 161	; Note: 57.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 28	; Note: 52.
	defb 63, 21	; Escaped note: 21.
	defb 31	; Note: 55.
	defb 63, 21	; Escaped note: 21.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 81	; Escaped note: 81.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 63, 81	; Escaped note: 81.
	defb 63, 21	; Escaped note: 21.
	defb 36	; Note: 60.
	defb 63, 21	; Escaped note: 21.
	defb 33	; Note: 57.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 12	; Note: 36.
	defb 21	; Note: 45.
	defb 0	; Note: 24.
	defb 19	; Note: 43.
	defb 0	; Note: 24.
	defb 63, 19	; Escaped note: 19.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 19	; Escaped note: 19.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

Naksolaat_Subsong0_Track18
	defb 132	; Note: 28.
	defb 2	; New instrument: 1.
	defb 63, 79	; Escaped note: 79.
	defb 4	; Note: 28.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 149	; Note: 45.
	defb 2	; New instrument: 1.
	defb 16	; Note: 40.
	defb 63, 84	; Escaped note: 84.
	defb 4	; Note: 28.
	defb 63, 81	; Escaped note: 81.
	defb 4	; Note: 28.
	defb 26	; Note: 50.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 84	; Escaped note: 84.
	defb 2	; New instrument: 1.
	defb 16	; Note: 40.
	defb 63, 86	; Escaped note: 86.
	defb 2	; Note: 26.
	defb 19	; Note: 43.
	defb 2	; Note: 26.
	defb 21	; Note: 45.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 88	; Escaped note: 88.
	defb 2	; New instrument: 1.
	defb 14	; Note: 38.
	defb 63, 86	; Escaped note: 86.
	defb 2	; Note: 26.
	defb 63, 84	; Escaped note: 84.
	defb 2	; Note: 26.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 81	; Escaped note: 81.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 84	; Escaped note: 84.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 31	; Note: 55.
	defb 9	; Note: 33.
	defb 63, 81	; Escaped note: 81.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 161	; Note: 57.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 28	; Note: 52.
	defb 14	; Note: 38.
	defb 31	; Note: 55.
	defb 14	; Note: 38.
	defb 63, 79	; Escaped note: 79.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 191, 81	; Escaped note: 81.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 63, 81	; Escaped note: 81.
	defb 16	; Note: 40.
	defb 36	; Note: 60.
	defb 16	; Note: 40.
	defb 33	; Note: 57.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 159	; Note: 55.
	defb 2	; New instrument: 1.
	defb 12	; Note: 36.
	defb 21	; Note: 45.
	defb 9	; Note: 33.
	defb 19	; Note: 43.
	defb 9	; Note: 33.
	defb 63, 19	; Escaped note: 19.
	defb 12	; Note: 36.
	defb 9	; Note: 33.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 0	; Note: 24.

